@startuml
'https://plantuml.com/class-diagram

' The application class will follow the requirements of containing only the launch command, and
' enough code to launch the first GUI in the start method.
class MainApplication
{
main()
start(Stage stage)
}

' This class deals with all the events inside the app and how they will relate to the
' other bits of code associated with the app
class MainFXMLController
{
Button addButton
Button deleteButton
Button editButton

ListView<?> mainList
MenuBar appMenuBar

MenuItem loadButton
MenuItem saveButton
MenuItem newListItem
MenuItem closeButton


addListItem()
attemptCloseApp()
createNewList()
deleteListItem()
editListItem()
loadList()
saveCurrentList()
}
' This will be an object that holds a list of objects that contain data about each
' item in the list, hence the name listItem
class ListItem
{
    String listGoal
    boolean isComplete
    String date
    ListItem(String listGoal, boolean isComplete, String date)
}
' This object will hold all the properties of an item in the to do list.
class List
{
    List(ListItem[])
}
MainApplication <|-- MainFXMLController
List <|-- ListItem

@enduml